### ISSUE TITLE
Use original file extension in OBJ filename

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_binary_object#22]
OBJ datastream is given extension based on MIMEtype, and for certain types of file (e.g. SAV, for SPSS files) the un-desired extension ".bin" is added.

Would be nice if we had the choice to simply use the uploaded file's original extension rather than adding a new one.

**Comment by willtp87** [comment]
The feature you are requesting would be best implemented in Islandora proper or a stand alone module.  However, I'm not sure that it is the best approach.  Support for mimes can be added using [hook_file_mimetype_mapping_alter](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_file_mimetype_mapping_alter/7.x) if you are interested in creating a less intensive pull request.
