### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by rosiel** [Islandora-Labs/islandora_binary_object#25]
It's great that this repo has a CONTRIBUTING.md. However, it suggests creating Jira issues, and being in Labs this doesn't exist as a Jira component. There's a whole section on release PRs, and this component is not in release. There's also no mention of the "rules of merging" (who can merge whose PRs and how quickly) which was - I think - the variable that we wanted to let Labs component managers define in their own contributing.md files in order to facilitate faster development (if they so desired).

We have some PRs we'd like to submit, so we want to make sure that we understand the desired workflow before we do!

**Comment by willtp87** [comment]
@manez Can we have an appropriate component added to Jira if there isn't already one? @rosiel I'll look into removing the release info from the file. Information on workflow is [linked in the file](https://github.com/Islandora-Labs/islandora_binary_object/blame/7.x/CONTRIBUTING.md#L80) . More links branch from there but he TLDR is that this repo follows most of the same rules as repos in the Islandora organization save for [this](https://github.com/Islandora-Labs/islandora_binary_object/commit/67e3e607ca0e0b7087fe7c8cc050117a08bd5a44) meaning that [this](https://github.com/Islandora/islandora/wiki/Islandora-Committers-Workflow) does not apply. I'm seeing that the document doesn't explicitly mention who can merge but the intent is along the lines of "Any Committer who feels confident with the code change may merge the pull request." I'll look into adding that. Will these changes address your concerns?

**Comment by manez** [comment]
@willtp87 we can get Labs components added in JIRA as needed 👍

**Comment by rosiel** [comment]
I can see the argument that because it's covered by the [Labs Workflow](https://github.com/Islandora/islandora/wiki/Islandora-Labs-Maintainer-Workflow), the [Islandora Workflow](https://github.com/Islandora/islandora/wiki/Islandora-Committers-Workflow) doesn't apply. No defined workflow = no restrictions. Does the line in Git Guidelines and Best Practices (which you referred to as "information on workflow") about not merging your own PRs apply? I am guessing so?

(My own frustration with this, and with defining one for my Labs components, led me to write this [template](https://github.com/rosiel/Contributing-Templates/blob/master/CONTRIBUTING.md) which is far from perfect but outlines the questions that I felt needed to be defined, in accordance with the [Labs Workflow](https://github.com/Islandora-Labs/islandora_binary_object/commit/67e3e607ca0e0b7087fe7c8cc050117a08bd5a44) doc.)

@manez and @willtp87, are "Committers", in 7.x the same group of people as Labs-Committers?

**Comment by manez** [comment]
@rosiel Labs Committers are the same as 7.x Committers. Or at least they should be.

**Comment by willtp87** [comment]
"Does ... not merging your own PRs apply?" Yes, that's the intent.
