### ISSUE TITLE
No download or thumbnail when part of Compound Object

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_binary_object#34]
If you create a Binary Object on its own, it looks great... A default thumbnail, and a downloadable link. 
![screen shot 2019-02-11 at 11 40 43 am](https://user-images.githubusercontent.com/6069170/52578289-f0b0d600-2df1-11e9-9f6f-419f477d632e.png)

But if you make that same object part of a Compound Object, all of that good stuff disappears:
![screen shot 2019-02-11 at 11 42 36 am](https://user-images.githubusercontent.com/6069170/52578403-28b81900-2df2-11e9-95c8-500350a88bae.png)

Why does it display so poorly as a Compound child, given that these are designed to be part of Compound Objects?

**Comment by mjordan** [comment]
https://jira.duraspace.org/browse/ISLANDORA-2266 possibly related?

**Comment by bondjimbond** [comment]
@mjordan I don't see the connection, but I'm open to an explanation!

**Comment by bondjimbond** [comment]
So are you saying this is a problem with the Compound SP and not the Binary SP?

**Comment by mjordan** [comment]
@bondjimbond I'm not sure what I'm saying. Scratch my comment about that JIRA ticket - I posted it in haste without thinking too much about it. Sorry for the red herring.

**Comment by bondjimbond** [comment]
Turns out the problem is actually with Islandora Compound Parent Metadata! I'll open a ticket there...
